// Generated from apps/api/src/news_insight/taxonomy/catalog.py — keep in sync.
export const TAXONOMY_REVISION = "2026-10-04.1";

export const FIELD_LABEL: Record<string, string> = {
  "ai_data": "AI·데이터",
  "semiconductor": "반도체",
  "mobile_edge": "모바일·엣지",
  "display_media": "디스플레이·미디어",
  "network_comms": "네트워크·통신",
  "cloud_infra": "클라우드·인프라",
  "software_dev": "소프트웨어·개발",
  "open_source": "오픈소스·생태계",
  "security_privacy": "보안·프라이버시",
  "robotics_auto": "로보틱스·자율시스템",
  "manufacturing_supply": "제조·공급망",
  "product_market": "제품·시장",
  "finance_investment": "재무·투자",
  "policy_ip_standards": "정책·IP·표준",
  "emerging_science": "미래과학·지속가능성"
};

export const THEME_LABEL: Record<string, string> = {
  "ai_data__generative_foundation": "생성형 AI·기반모델",
  "ai_data__ai_agents": "AI 에이전트",
  "ai_data__multimodal": "멀티모달·비전·음성",
  "ai_data__edge_ai": "온디바이스·엣지 AI",
  "ai_data__mlops_data": "MLOps·데이터 플랫폼",
  "semiconductor__memory_hbm_cxl": "메모리·HBM·CXL",
  "semiconductor__foundry_process": "파운드리·미세공정",
  "semiconductor__soc_npu": "System LSI·SoC·NPU",
  "semiconductor__advanced_packaging": "첨단 패키징·칩렛",
  "semiconductor__eda_material_equipment": "EDA·소재·장비",
  "mobile_edge__android_mobile_os": "Android·모바일 OS",
  "mobile_edge__smartphone_compute": "스마트폰·모바일 컴퓨팅",
  "mobile_edge__edge_computing": "엣지 컴퓨팅",
  "mobile_edge__wearable_health": "웨어러블·디지털 헬스",
  "mobile_edge__app_service_ecosystem": "앱·서비스 생태계",
  "display_media__oled_microled": "OLED·MicroLED",
  "display_media__display_imaging": "디스플레이 구동·영상처리",
  "display_media__tv_media_platform": "TV·미디어 플랫폼",
  "display_media__xr_spatial_display": "XR·공간 디스플레이",
  "display_media__codec_content": "코덱·콘텐츠 기술",
  "network_comms__fiveg_sixg": "5G·6G",
  "network_comms__ran_core": "RAN·코어망",
  "network_comms__short_range_wireless": "Wi-Fi·UWB·Bluetooth",
  "network_comms__satellite_ntn": "위성·NTN",
  "network_comms__network_automation_security": "네트워크 자동화·보안",
  "cloud_infra__public_hybrid_cloud": "퍼블릭·하이브리드 클라우드",
  "cloud_infra__kubernetes_container": "Kubernetes·컨테이너",
  "cloud_infra__platform_engineering": "플랫폼 엔지니어링",
  "cloud_infra__sre_observability": "SRE·관측성",
  "cloud_infra__finops_green_compute": "FinOps·그린 컴퓨팅",
  "software_dev__language_compiler": "프로그래밍 언어·컴파일러",
  "software_dev__web_app_framework": "웹·앱 프레임워크",
  "software_dev__api_distributed": "API·분산 시스템",
  "software_dev__cicd_testing": "CI/CD·테스트",
  "software_dev__developer_experience": "개발자 경험·도구",
  "open_source__project_trends": "프로젝트 트렌드",
  "open_source__community_health": "메인테이너·커뮤니티 건강성",
  "open_source__license_governance": "라이선스·거버넌스",
  "open_source__supply_chain_sbom": "공급망·SBOM",
  "open_source__enterprise_adoption": "기업 채택·기여",
  "security_privacy__application_security": "애플리케이션 보안",
  "security_privacy__cloud_security": "클라우드·인프라 보안",
  "security_privacy__device_hardware_security": "디바이스·하드웨어 보안",
  "security_privacy__identity_zero_trust": "ID·제로트러스트",
  "security_privacy__privacy_cryptography": "프라이버시·암호기술",
  "robotics_auto__humanoid_service_robot": "휴머노이드·서비스 로봇",
  "robotics_auto__embodied_ai": "Embodied AI",
  "robotics_auto__autonomous_adas": "자율주행·ADAS",
  "robotics_auto__drone_unmanned": "드론·무인이동체",
  "robotics_auto__sensor_control_twin": "센서·제어·디지털 트윈",
  "manufacturing_supply__smart_factory": "스마트 팩토리",
  "manufacturing_supply__industrial_ai": "산업 AI·자동화",
  "manufacturing_supply__scm_logistics": "SCM·물류",
  "manufacturing_supply__quality_yield": "품질·수율",
  "manufacturing_supply__supply_resilience": "공급망 회복탄력성",
  "product_market__consumer_electronics": "소비자 전자",
  "product_market__b2b_enterprise": "B2B·엔터프라이즈",
  "product_market__customer_design": "고객경험·디자인",
  "product_market__competition_partnership": "경쟁·파트너십·M&A",
  "product_market__pricing_revenue": "가격·수익모델",
  "finance_investment__macro_fx": "거시경제·환율",
  "finance_investment__capex_investment": "CAPEX·설비투자",
  "finance_investment__cost_economics": "원가·단위경제성",
  "finance_investment__valuation_ir": "기업가치·IR",
  "finance_investment__financial_risk": "재무·사업 리스크",
  "policy_ip_standards__technology_regulation": "기술 규제",
  "policy_ip_standards__ai_governance_ethics": "AI 거버넌스·윤리",
  "policy_ip_standards__patent_litigation": "특허·소송·라이선스",
  "policy_ip_standards__international_standards": "국제표준",
  "policy_ip_standards__export_geopolitics": "수출통제·지정학",
  "emerging_science__quantum_technology": "양자기술",
  "emerging_science__neuromorphic_photonic": "뉴로모픽·포토닉스",
  "emerging_science__advanced_materials": "첨단소재",
  "emerging_science__battery_energy": "배터리·에너지",
  "emerging_science__carbon_circularity": "탄소·순환경제"
};

export const BUSINESS_LABEL: Record<string, string> = {
  "mx": "MX · 모바일·온디바이스 AI",
  "vd": "VD · 디스플레이·영상",
  "da": "DA · 생활가전·홈로봇",
  "networks": "Networks · 5G Adv·6G",
  "health": "Health · 디지털 헬스·의료기기",
  "harman": "Harman · 전장·SDV"
};

export const IMPACT_LABEL: Record<string, string> = {
  "opportunity": "기회",
  "risk": "위험",
  "watch": "관찰"
};

export const SCOPE_LABEL: Record<string, string> = {
  "dx": "DX 제품·기술",
  "dx_dependency": "DX 기술 의존성",
  "excluded": "반도체 자산 투자(제외)",
  "irrelevant": "무관"
};
