BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY;
SET LOCAL statement_timeout='30s';
SELECT jsonb_agg(t) FROM (SELECT s.key,e.stage,e.outcome,e.reasons FROM sources s JOIN LATERAL (SELECT * FROM source_validation_events v WHERE v.source_id=s.id ORDER BY v.id DESC LIMIT 1) e ON true WHERE s.key IN ('samsung-newsroom-kr','samsung-newsroom-global','ieee-spectrum','nvidia-blog','openai-news')) t;
SELECT jsonb_agg(t) FROM (SELECT s.key,c.status,c.taxonomy_revision,c.scope,count(*) n FROM items i JOIN sources s ON s.id=i.source_id LEFT JOIN item_cards c ON c.item_id=i.id WHERE s.key IN ('ieee-spectrum','nvidia-blog','nvidia-developer-blog','openai-news','apple-newsroom') GROUP BY 1,2,3,4 ORDER BY 1,5 DESC) t;
WITH a AS (SELECT s.key,s.official_domain,c.field,t.theme,count(*) n FROM items i JOIN sources s ON s.id=i.source_id JOIN item_cards c ON c.item_id=i.id CROSS JOIN LATERAL jsonb_array_elements_text(c.themes) t(theme) WHERE i.first_seen_at>now()-interval '7 days' AND c.status='ready' AND c.scope IN ('dx','dx_dependency') AND c.taxonomy_revision LIKE '2026-10-05.%' AND (i.published_at IS NULL OR i.published_at>=i.first_seen_at-interval '30 days') GROUP BY 1,2,3,4) SELECT jsonb_agg(t) FROM (SELECT theme,sum(n) n,count(distinct key) channels,count(distinct official_domain) catalog_domains,max(n) top_channel_n,(array_agg(key ORDER BY n DESC))[1] top_channel FROM a GROUP BY 1 ORDER BY 2 DESC) t;
SELECT jsonb_agg(t) FROM (SELECT s.status,count(*) n FROM items i JOIN sources s ON s.id=i.source_id JOIN item_cards c ON c.item_id=i.id WHERE c.status='ready' AND c.scope IN ('dx','dx_dependency') AND c.taxonomy_revision LIKE '2026-10-05.%' AND (i.published_at IS NULL OR i.published_at>=i.first_seen_at-interval '30 days') GROUP BY 1) t;
SELECT jsonb_agg(t) FROM (SELECT s.key,i.title,i.url,i.published_at FROM items i JOIN sources s ON s.id=i.source_id WHERE s.key in ('infineon-news-web','waymo-web','zigbee2mqtt-web') ORDER BY md5(i.id::text) LIMIT 18) t;
SELECT jsonb_agg(t) FROM (SELECT s.key,i.canonical_url,count(*) n FROM items i JOIN sources s ON s.id=i.source_id WHERE s.access_method IN ('atproto','activitypub') GROUP BY 1,2 HAVING count(*)>1 ORDER BY 3 DESC LIMIT 5) t;
COMMIT;
