BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY;
SET LOCAL statement_timeout='40s';
SELECT jsonb_build_object('checked_at',now(),'first_fetch',(select min(started_at) from fetch_runs),'last_fetch',(select max(started_at) from fetch_runs));
WITH f AS (SELECT source_id,count(*) runs,count(*) filter(where outcome='success') success,count(*) filter(where outcome='not_modified') not_modified,count(*) filter(where outcome in ('failed','dead_lettered')) errors,count(*) filter(where outcome='skipped') skipped,sum(items_seen) seen,sum(items_new) new,sum(items_incomplete) incomplete,max(started_at) latest_run FROM fetch_runs WHERE started_at>now()-interval '24 hours' GROUP BY 1), i AS (SELECT source_id,count(*) items,count(*) filter(where published_at<first_seen_at-interval '30 days') old FROM items GROUP BY 1)
SELECT jsonb_agg(t) FROM (SELECT s.id,s.key,s.name,s.access_method,s.status,s.validation_stage,s.paused_reason,s.endpoint_url,r.last_success_at,r.last_attempt_at,r.next_due_at,r.interval_seconds,r.consecutive_failures,r.consecutive_idle,r.lease_until,f.runs,f.success,f.not_modified,f.errors,f.skipped,f.seen,f.new,f.incomplete,f.latest_run,i.items,i.old,v.stage last_validation_stage,v.outcome last_validation_outcome,v.reasons last_validation_reasons,v.created_at last_validation_at,lf.outcome last_fetch_outcome,lf.error_code last_error,lf.http_status last_http,lf.items_seen last_items_seen FROM sources s LEFT JOIN source_runtimes r ON r.source_id=s.id LEFT JOIN f ON f.source_id=s.id LEFT JOIN i ON i.source_id=s.id LEFT JOIN LATERAL (SELECT stage,outcome,reasons,created_at FROM source_validation_events WHERE source_id=s.id ORDER BY id DESC LIMIT 1) v ON true LEFT JOIN LATERAL (SELECT outcome,error_code,http_status,items_seen FROM fetch_runs WHERE source_id=s.id ORDER BY started_at DESC,id DESC LIMIT 1) lf ON true ORDER BY s.key) t;
SELECT jsonb_agg(t) FROM (SELECT outcome,error_code,count(*) n FROM fetch_runs WHERE started_at>now()-interval '24 hours' GROUP BY 1,2 ORDER BY 3 DESC) t;
SELECT jsonb_agg(t) FROM (SELECT s.key,d.error_code,count(*) n,max(d.created_at) latest FROM dead_letters d JOIN sources s ON s.id=d.source_id WHERE d.resolved_at IS NULL GROUP BY 1,2 ORDER BY 3 DESC) t;
SELECT jsonb_agg(t) FROM (SELECT outcome,count(*) n FROM fetch_runs WHERE started_at>now()-interval '1 hour' GROUP BY 1) t;
COMMIT;
